drop table if exists cms.generalpayments;
use cms;
create external  table generalpayments ( 
change_type string,
covered_recipient_type string,
teaching_hospital_ccn string,
teaching_hospital_id string,
teaching_hospital_name string,
physician_profile_id string,
physician_first_name string,
physician_middle_name string,
physician_last_name string,
physician_name_suffix string,
recipient_primary_business_street_address_line1 string,
recipient_primary_business_street_address_line2 string,
recipient_city string,
recipient_state string,
recipient_zip_code string,
recipient_country string,
recipient_province string,
recipient_postal_code string,
physician_primary_type string,
physician_specialty string,
physician_license_state_code1 string,
physician_license_state_code2 string,
physician_license_state_code3 string,
physician_license_state_code4 string,
physician_license_state_code5 string,
submitting_applicable_manufacturer_or_applicable_gpo_name string,
applicable_manufacturer_or_applicable_gpo_making_payment_id string,
applicable_manufacturer_or_applicable_gpo_making_payment_name string,
applicable_manufacturer_or_applicable_gpo_making_payment_state string,
applicable_manufacturer_or_applicable_gpo_making_payment_country string,
total_amount_of_payment_usdollars decimal ( 10,2),
date_of_payment string,
number_of_payments_included_in_total_amount int,
form_of_payment_or_transfer_of_value string,
nature_of_payment_or_transfer_of_value string,
city_of_travel string,
state_of_travel string,
country_of_travel string,
physician_ownership_indicator string,
third_party_payment_recipient_indicator string,
name_of_third_party_entity_receiving_payment_or_transfer_of_value string,
charity_indicator string,
third_party_equals_covered_recipient_indicator string,
contextual_information string,
delay_in_publication_indicator string,
record_id string,
dispute_status_for_publication string,
related_product_indicator string,
covered_or_noncovered_indicator_1 string,
indicate_drug_or_biological_or_device_or_medical_supply_1 string,
product_category_or_therapeutic_area_1 string,
name_of_drug_or_biological_or_device_or_medical_supply_1 string,
associated_drug_or_biological_ndc_1 string,
covered_or_noncovered_indicator_2 string,
indicate_drug_or_biological_or_device_or_medical_supply_2 string,
product_category_or_therapeutic_area_2 string,
name_of_drug_or_biological_or_device_or_medical_supply_2 string,
associated_drug_or_biological_ndc_2 string,
covered_or_noncovered_indicator_3 string,
indicate_drug_or_biological_or_device_or_medical_supply_3 string,
product_category_or_therapeutic_area_3 string,
name_of_drug_or_biological_or_device_or_medical_supply_3 string,
associated_drug_or_biological_ndc_3 string,
covered_or_noncovered_indicator_4 string,
indicate_drug_or_biological_or_device_or_medical_supply_4 string,
product_category_or_therapeutic_area_4 string,
name_of_drug_or_biological_or_device_or_medical_supply_4 string,
associated_drug_or_biological_ndc_4 string,
covered_or_noncovered_indicator_5 string,
indicate_drug_or_biological_or_device_or_medical_supply_5 string,
product_category_or_therapeutic_area_5 string,
name_of_drug_or_biological_or_device_or_medical_supply_5 string,
associated_drug_or_biological_ndc_5 string,
program_year string,
payment_publication_date string
)
row format delimited
fields terminated by ','
stored as textfile
location '/user/marty/cms.db/generalpayments'
;


select * from generalpayments limit 3;
-- "new","covered recipient physician",,,,"132655","gregg","d","alzate",,"8745 aero drive","ste 200","san diego","ca","92123","united states",,,"medical doctor","allopathic & osteopathic physicians|radiology|diagnostic radiology","ca",,,,,"dfine, inc","100000000326","dfine, inc","ca","united states",90.87,"02/12/2016","1","in-kind items and services","food and beverage",,,,"no","no third party payment",,,,,"no","346039438","no","yes","covered","device","radiology","stabilit",,"covered","device","radiology","star tumor ablation system",,,,,,,,,,,,,,,,,"2016","06/30/2017"
